# Generated by Django 3.0.4 on 2020-10-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id_room', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('number_of_sensors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id_temp', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('value_temp', models.FloatField(default=0.0)),
                ('date_temp', models.DateTimeField(auto_now_add=True)),
                ('time_temp', models.TimeField(auto_now_add=True)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.room')),
            ],
        ),
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id_hum', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('value_hum', models.FloatField(default=0.0)),
                ('date_hum', models.DateTimeField(auto_now_add=True)),
                ('time_hum', models.TimeField(auto_now_add=True)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.room')),
            ],
        ),
        migrations.CreateModel(
            name='co2',
            fields=[
                ('id_co2', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('value_co2', models.FloatField(default=0.0)),
                ('date_co2', models.DateTimeField(auto_now_add=True)),
                ('time_co2', models.TimeField(auto_now_add=True)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.room')),
            ],
        ),
        migrations.CreateModel(
            name='air_press',
            fields=[
                ('id_air', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('value_air', models.FloatField(default=0.0)),
                ('date_air', models.DateTimeField(auto_now_add=True)),
                ('time_air', models.TimeField(auto_now_add=True)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.room')),
            ],
        ),
    ]
