# Generated by Django 3.0.4 on 2020-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_pass',
            field=models.CharField(default='.....', max_length=30),
        ),
    ]
